version: "3"


services:
  backend:
    image: limon-backend
    container_name: backend
    build: .
    user: appuser
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./service:/app
    depends_on:
      - redis
      - postgresql


  postgresql:
    image: postgres:14.1-alpine
    hostname: $${POSTGRES_HOST}
    container_name: postgresql
    env_file: .env
    ports:
      - 8001:5432
    volumes:
      - pg-data-limon:/var/lib/postgresql/data


  redis:
    image: redis:6.2-alpine
    hostname: $${REDIS_HOST}
    container_name: redis
    env_file: .env
    ports:
      - 8002:6379


volumes:
  pg-data-limon:
