# Generated by Django 4.0.1 on 2022-05-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_teams_delete_projectteam'),
        ('user', '0005_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
