# Generated by Django 4.0.1 on 2022-05-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_projects_delete_productproject'),
        ('project', '0002_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.ForeignKey(default='b1ebee89-d07a-4705-8116-1979f77a5818', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
