# Generated by Django 4.0.1 on 2022-05-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_organization_project_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='teams',
        ),
        migrations.DeleteModel(
            name='ProjectTeam',
        ),
    ]
