# Generated by Django 4.0.1 on 2022-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(default='default', upload_to='images/logo/'),
            preserve_default=False,
        ),
    ]
