# Generated by Django 4.0.1 on 2022-05-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='slug',
            field=models.SlugField(max_length=32, null=True),
        ),
    ]
